// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
    public const string achievementPc1 = "CgkImviytJoSEAIQAg"; // 기본 컴퓨터 오너
    public const string achievementPc2 = "CgkImviytJoSEAIQAw"; // 고성능 컴퓨터 오너
    public const string achievementPc3 = "CgkImviytJoSEAIQBA"; // 슈퍼 컴퓨터 오너
    public const string achievementPc4 = "CgkImviytJoSEAIQBQ"; // 양자 컴퓨터 오너

    public const string achievementBtc1 = "CgkImviytJoSEAIQBg"; // 일반 투자자
    public const string achievementBtc2 = "CgkImviytJoSEAIQBw"; // 슈퍼 개미
    public const string achievementBtc3 = "CgkImviytJoSEAIQCA"; // 자본가
    public const string achievementBtc4 = "CgkImviytJoSEAIQCQ"; // 슈퍼 리치
}

